# Package Overview
package_name: regression_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (charges)
target: charges

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

features:
  - age
  - sex
  - bmi
  - children
  - smoker
  - region


# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

alpha: 0.001

# variables to log transform
numericals_yeo_vars:
  - bmi

# variables to map
sex_vars:
  - sex

smoker_vars:
  - smoker

region_vars:
  - region

categorical_vars:
  - sex
  - smoker
  - region

# variable mappings
sex_mappings:
  male: 0
  female: 1

smoker_mappings:
  no: 0
  yes: 1

region_mappings:
  southwest: 0
  southeast: 1
  northwest: 2
  northeast: 3
